language: php

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - composer update
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover UnitTest tests/Faker/fakerCVETest.php

php:
  - 7.1
